package view

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/Breina/Jenking/internal/jenkins/pipelinesyntax"
)

// vimRuntime materialises a per-build vim runtime directory holding:
//   - after/syntax/groovy.vim   — keyword overlays for Jenkins steps + DSL
//   - plugin/jenking.vim        — omnifunc + completion / quickfix wiring
//
// The directory is layered on top of the user's vimrc via `--cmd 'set
// rtp^=…'` so the user's normal config keeps working untouched.
//
// runtimeDir is also where the in-vim validation daemon (Slice 4) drops its
// sentinel + errorformat files — those filenames are pre-declared here so
// both layers agree.
type vimRuntime struct {
	dir       string // absolute path to the runtime root
	bufferTmp string // sentinel buffer.groovy path (BufWritePost target)
	errorsQF  string // quickfix file the TUI writes back
}

// jenkingCacheDir returns the on-disk root for jenking's editor scratch space.
func jenkingCacheDir() (string, error) {
	base, err := os.UserCacheDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(base, "jenking", "vim"), nil
}

// buildRuntimeKey returns a stable, fs-safe directory name for a single
// (jobPath, buildNumber) pair.
func buildRuntimeKey(jobPath string, buildNum int) string {
	sum := sha256.Sum256([]byte(fmt.Sprintf("%s#%d", jobPath, buildNum)))
	return hex.EncodeToString(sum[:8])
}

// writeVimRuntime regenerates the per-build runtime directory. Idempotent:
// re-running on the same (jobPath, buildNum, sym) overwrites in place.
//
// sym may be nil — in that case the syntax overlay is empty and the omnifunc
// returns no matches, but vim still launches fine.
func writeVimRuntime(jobPath string, buildNum int, sym *pipelinesyntax.Symbols) (*vimRuntime, error) {
	root, err := jenkingCacheDir()
	if err != nil {
		return nil, err
	}
	dir := filepath.Join(root, buildRuntimeKey(jobPath, buildNum))
	for _, sub := range [][]string{{"after", "syntax"}, {"plugin"}, {"autoload"}} {
		if err := os.MkdirAll(filepath.Join(append([]string{dir}, sub...)...), 0o700); err != nil {
			return nil, err
		}
	}

	if err := os.WriteFile(
		filepath.Join(dir, "after", "syntax", "groovy.vim"),
		[]byte(renderSyntaxOverlay(sym)), 0o600,
	); err != nil {
		return nil, err
	}

	rt := &vimRuntime{
		dir:       dir,
		bufferTmp: filepath.Join(dir, "buffer.groovy"),
		errorsQF:  filepath.Join(dir, "errors.qf"),
	}
	// `jenking#X` style functions must live under autoload/<name>.vim — vim
	// enforces this (E746). plugin/jenking.vim only wires autocmds + globals.
	if err := os.WriteFile(
		filepath.Join(dir, "autoload", "jenking.vim"),
		[]byte(renderAutoloadVim(sym, rt)), 0o600,
	); err != nil {
		return nil, err
	}
	if err := os.WriteFile(
		filepath.Join(dir, "plugin", "jenking.vim"),
		[]byte(renderPluginVim(rt)), 0o600,
	); err != nil {
		return nil, err
	}
	return rt, nil
}

// renderSyntaxOverlay emits Vim `syntax keyword` declarations + highlight
// links for the build's symbol set. Loaded from `after/syntax/groovy.vim`
// so it stacks on top of vim's builtin groovy syntax (or whichever plugin
// the user has) without replacing it.
func renderSyntaxOverlay(sym *pipelinesyntax.Symbols) string {
	var b strings.Builder
	b.WriteString(`" Generated by jenking — per-build Jenkins symbol overlay.
" Do not edit; regenerated on every edit session.
"
" Loaded as after/syntax/groovy.vim so it runs once vim's builtin groovy
" syntax has finished. We use 'syntax match' rather than 'syntax keyword'
" because the builtin syntax may already have classified names like sh or
" archive under its own group — 'syntax match' overrides regardless of
" pre-existing keyword entries, while 'syntax keyword' silently no-ops in
" that case.

`)

	dsl := pipelinesyntax.DefaultDSLKeywords
	if sym != nil && len(sym.DSLKeywords) > 0 {
		dsl = sym.DSLKeywords
	}
	writeMatchAlternation(&b, "jenkingDSL", dsl)

	if sym != nil {
		stepNames := make([]string, 0, len(sym.Steps))
		for _, s := range sym.Steps {
			stepNames = append(stepNames, s.Name)
		}
		writeMatchAlternation(&b, "jenkingStep", stepNames)

		globalNames := make([]string, 0, len(sym.Globals))
		memberSet := map[string]struct{}{}
		for _, g := range sym.Globals {
			globalNames = append(globalNames, g.Name)
			for _, m := range g.Members {
				memberSet[m.Name] = struct{}{}
			}
		}
		writeMatchAlternation(&b, "jenkingGlobal", globalNames)

		// Library member names declared in user GDSL — `setVersion`, `goal`,
		// `tag`, etc. Match only after a dot so they don't repaint generic
		// words elsewhere in the file.
		if len(memberSet) > 0 {
			members := make([]string, 0, len(memberSet))
			for m := range memberSet {
				if isVimKeywordSafe(m) {
					members = append(members, m)
				}
			}
			if len(members) > 0 {
				fmt.Fprintf(&b, "syntax match jenkingMember /\\.\\@<=\\<\\(%s\\)\\>/\n",
					strings.Join(members, `\|`))
			}
		}

		// Receiver names that participate in `<name>.<member>` calls get a
		// distinct highlight when followed by a dot.
		recvNames := make([]string, 0)
		for _, g := range sym.Globals {
			if len(g.Members) > 0 && isVimKeywordSafe(g.Name) {
				recvNames = append(recvNames, g.Name)
			}
		}
		if len(recvNames) > 0 {
			fmt.Fprintf(&b, "syntax match jenkingReceiver /\\<\\(%s\\)\\>\\ze\\./\n",
				strings.Join(recvNames, `\|`))
		}
	}

	// Link to distinctive default groups. Most terminal colorschemes give
	// these visibly different colors, so users don't need a custom theme.
	b.WriteString(`
highlight default link jenkingDSL      Statement
highlight default link jenkingStep     Function
highlight default link jenkingGlobal   Constant
highlight default link jenkingMember   Special
highlight default link jenkingReceiver Type
`)
	return b.String()
}

// writeMatchAlternation emits `syntax match <group> /\<\(a\|b\|c\)\>/` lines.
// Chunked so vim's command-line length cap is never tripped. Empty / unsafe
// names are dropped (those vim regex would either misparse or fail on).
func writeMatchAlternation(b *strings.Builder, group string, names []string) {
	if len(names) == 0 {
		return
	}
	seen := make(map[string]struct{}, len(names))
	const perLine = 80
	row := make([]string, 0, perLine)
	flush := func() {
		if len(row) == 0 {
			return
		}
		fmt.Fprintf(b, "syntax match %s /\\<\\(%s\\)\\>/\n", group, strings.Join(row, `\|`))
		row = row[:0]
	}
	for _, n := range names {
		n = strings.TrimSpace(n)
		if n == "" || !isVimKeywordSafe(n) {
			continue
		}
		if _, ok := seen[n]; ok {
			continue
		}
		seen[n] = struct{}{}
		row = append(row, n)
		if len(row) >= perLine {
			flush()
		}
	}
	flush()
}

// writeKeywordChunks emits `syntax keyword <group> a b c …` lines, chunked
// to stay under vim's command-line length limits. Empty/duplicate names are
// dropped silently.
func writeKeywordChunks(b *strings.Builder, group string, names []string) {
	if len(names) == 0 {
		return
	}
	seen := make(map[string]struct{}, len(names))
	const perLine = 50
	row := make([]string, 0, perLine)
	flush := func() {
		if len(row) == 0 {
			return
		}
		fmt.Fprintf(b, "syntax keyword %s %s\n", group, strings.Join(row, " "))
		row = row[:0]
	}
	for _, n := range names {
		n = strings.TrimSpace(n)
		if n == "" || !isVimKeywordSafe(n) {
			continue
		}
		if _, ok := seen[n]; ok {
			continue
		}
		seen[n] = struct{}{}
		row = append(row, n)
		if len(row) >= perLine {
			flush()
		}
	}
	flush()
}

// isVimKeywordSafe reports whether a name can be passed to `syntax keyword`
// without escaping (alnum + underscore only).
func isVimKeywordSafe(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		if !(r == '_' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

// renderAutoloadVim emits autoload/jenking.vim. Loaded on demand the first
// time anything calls a `jenking#X` function.
func renderAutoloadVim(sym *pipelinesyntax.Symbols, rt *vimRuntime) string {
	var b strings.Builder
	b.WriteString(`" Generated by jenking — autoload/jenking.vim.
let s:symbols = []
let s:steps_count = 0
let s:globals_count = 0
let s:members = {}
let s:receivers = []
let s:call_params = {}
`)
	emitParamList := func(params []pipelinesyntax.Param) string {
		if len(params) == 0 {
			return "[]"
		}
		names := make([]string, len(params))
		for i, p := range params {
			names[i] = vimStr(p.Name)
		}
		return "[" + strings.Join(names, ", ") + "]"
	}
	if sym != nil {
		fmt.Fprintf(&b, "let s:steps_count = %d\n", len(sym.Steps))
		fmt.Fprintf(&b, "let s:globals_count = %d\n", len(sym.Globals))
		for _, s := range sym.Steps {
			fmt.Fprintf(&b, "call add(s:symbols, {'word': %s, 'abbr': %s, 'menu': %s, 'info': %s, 'kind': 'f'})\n",
				vimStr(s.Name), vimStr(s.Name), vimStr(s.Signature()), vimStr(s.Doc),
			)
			// Param info keyed by call name. If multiple overloads exist
			// (e.g. positional + namedParams sh), the LATER entry wins —
			// Jenkins gdsl emits namedParams form last, which has richer info.
			fmt.Fprintf(&b, "let s:call_params[%s] = %s\n", vimStr(s.Name), emitParamList(s.Params))
		}
		for _, g := range sym.Globals {
			fmt.Fprintf(&b, "call add(s:symbols, {'word': %s, 'abbr': %s, 'menu': %s, 'info': %s, 'kind': 'v'})\n",
				vimStr(g.Name), vimStr(g.Name), vimStr("global"), vimStr(g.Doc),
			)
			if len(g.Members) == 0 {
				continue
			}
			fmt.Fprintf(&b, "let s:members[%s] = []\n", vimStr(g.Name))
			fmt.Fprintf(&b, "call add(s:receivers, %s)\n", vimStr(g.Name))
			for _, m := range g.Members {
				menu := m.Signature
				if menu == "" {
					menu = m.Name
				}
				fmt.Fprintf(&b, "call add(s:members[%s], {'word': %s, 'abbr': %s, 'menu': %s, 'info': %s, 'kind': 'm'})\n",
					vimStr(g.Name), vimStr(m.Name), vimStr(m.Name), vimStr(menu), vimStr(m.Doc),
				)
				// Param info under "receiver.method" key for in-call mode.
				fmt.Fprintf(&b, "let s:call_params[%s] = %s\n",
					vimStr(g.Name+"."+m.Name), emitParamList(m.Params))
			}
		}
	}
	b.WriteString(`
" jenking#Receivers returns the list of global names that have scraped members.
" Used by the dot-trigger to decide whether to fire completion.
function! jenking#Receivers() abort
  return s:receivers
endfunction

" Find the receiver token immediately to the left of the cursor, if the char
" just before the cursor is a period. Returns '' otherwise.
function! s:receiver_at_cursor() abort
  let l:line = getline('.')
  let l:col = col('.') - 1
  if l:col <= 0 || l:line[l:col - 1] !=# '.'
    return ''
  endif
  let l:end = l:col - 1
  let l:start = l:end
  while l:start > 0 && l:line[l:start - 1] =~# '\k'
    let l:start -= 1
  endwhile
  return l:line[l:start : l:end - 1]
endfunction

" s:call_at_cursor walks backward from the cursor to detect whether we're
" inside an open call's argument list. Returns the dotted call name
" (e.g. maven.goal or sh) if so, otherwise empty. Scan respects nested
" parens and single-quoted strings — coarse, line-local only.
function! s:call_at_cursor() abort
  let l:line = getline('.')
  let l:col = col('.') - 2
  let l:depth = 0
  let l:in_str = 0
  while l:col >= 0
    let l:c = l:line[l:col]
    if l:in_str
      if l:c ==# "'"
        let l:in_str = 0
      endif
      let l:col -= 1
      continue
    endif
    if l:c ==# "'"
      let l:in_str = 1
    elseif l:c ==# ')'
      let l:depth += 1
    elseif l:c ==# '('
      if l:depth == 0
        " Found an unclosed open-paren. Token to its left is the call name.
        let l:end = l:col
        let l:start = l:end
        while l:start > 0 && (l:line[l:start - 1] =~# '\k' || l:line[l:start - 1] ==# '.')
          let l:start -= 1
        endwhile
        if l:start == l:end
          return ''
        endif
        return l:line[l:start : l:end - 1]
      endif
      let l:depth -= 1
    endif
    let l:col -= 1
  endwhile
  return ''
endfunction

function! jenking#Complete(findstart, base) abort
  if a:findstart
    let l:line = getline('.')
    let l:col = col('.') - 1
    while l:col > 0 && l:line[l:col - 1] =~# '\k'
      let l:col -= 1
    endwhile
    return l:col
  endif
  " Member mode: cursor is just after receiver-dot-prefix.
  let l:receiver = s:receiver_at_cursor()
  if l:receiver !=# '' && has_key(s:members, l:receiver)
    let l:matches = []
    for l:m in s:members[l:receiver]
      if a:base ==# '' || stridx(l:m.word, a:base) == 0
        call add(l:matches, l:m)
      endif
    endfor
    return l:matches
  endif
  " In-call mode: cursor is inside a method's argument list. Surface the
  " declared parameter names (best-effort — relies on the source GDSL
  " listing them; vague Map params yield a single 'argMap' suggestion).
  let l:call = s:call_at_cursor()
  if l:call !=# '' && has_key(s:call_params, l:call)
    let l:matches = []
    for l:name in s:call_params[l:call]
      if a:base ==# '' || stridx(l:name, a:base) == 0
        call add(l:matches, {'word': l:name, 'abbr': l:name, 'menu': l:call . '(' . l:name . ')', 'kind': 'a'})
      endif
    endfor
    if !empty(l:matches)
      return l:matches
    endif
  endif
  " Top-level mode.
  let l:matches = []
  for l:sym in s:symbols
    if a:base ==# '' || stridx(l:sym.word, a:base) == 0
      call add(l:matches, l:sym)
    endif
  endfor
  return l:matches
endfunction

" jenking#DotTrigger is bound to the . key. It returns the dot followed by
" Ctrl-X Ctrl-O when the word preceding the dot is a known receiver, so
" completion fires automatically for maven.<here> etc.
function! jenking#DotTrigger() abort
  let l:line = getline('.')
  let l:col = col('.') - 1
  let l:end = l:col
  let l:start = l:end
  while l:start > 0 && l:line[l:start - 1] =~# '\k'
    let l:start -= 1
  endwhile
  if l:start == l:end
    return '.'
  endif
  let l:word = l:line[l:start : l:end - 1]
  if has_key(s:members, l:word)
    return ".\<C-x>\<C-o>"
  endif
  return '.'
endfunction

function! jenking#Setup() abort
  syntax enable
  setlocal filetype=groovy
  " Explicitly source our syntax overlay. The standard after/syntax/groovy.vim
  " path relies on vim picking up our rtp entry AND firing groovy syntax for
  " the buffer; both can silently fail (rtp ordering quirks, user has
  " 'filetype off', vim with no groovy syntax shipped, …). Sourcing it
  " ourselves here guarantees the jenking* match groups exist on this
  " buffer regardless.
  if exists('g:jenking_runtime_dir')
    let s:overlay = g:jenking_runtime_dir . '/after/syntax/groovy.vim'
    if filereadable(s:overlay)
      execute 'silent! source ' . fnameescape(s:overlay)
    endif
  endif
  setlocal omnifunc=jenking#Complete
  setlocal completeopt=menuone,noinsert,preview
  if has('patch-8.1.1882') || has('nvim')
    try | setlocal completeopt+=popup | catch /./ | endtry
  endif
  " Newline copies the previous line's indentation; smartindent adds an
  " extra level after a line ending in an open brace.
  setlocal autoindent
  setlocal smartindent
  inoremap <buffer> <C-Space> <C-x><C-o>
  inoremap <buffer> <expr> . jenking#DotTrigger()
  inoremap <buffer> <expr> ( jenking#CallTrigger('(')
  inoremap <buffer> <expr> , jenking#CallTrigger(',')
  inoremap <buffer> <expr> <Space> jenking#SpaceTrigger()
  " Quickfix wiring (Slice 4): the TUI writes errors.qf as it validates.
  setlocal errorformat=%f:%l:%c:\ %m,%f:%l:\ %m
endfunction

" jenking#CallTrigger is bound to ( and , inside a buffer. After the typed
" character is inserted, if the cursor now sits inside a call whose name we
" know parameters for, fire omni completion to surface them.
function! jenking#CallTrigger(ch) abort
  return a:ch . "\<C-r>=jenking#MaybeOpenCall()\<CR>"
endfunction

function! jenking#MaybeOpenCall() abort
  let l:call = s:call_at_cursor()
  if l:call !=# '' && has_key(s:call_params, l:call) && !empty(s:call_params[l:call])
    call feedkeys("\<C-x>\<C-o>", 'n')
  endif
  return ''
endfunction

" Space after ( or , inside a known call: reopen the parameter popup. Any
" other context: behave as a literal space.
function! jenking#SpaceTrigger() abort
  let l:line = getline('.')
  let l:col = col('.') - 1
  if l:col > 0
    let l:prev = l:line[l:col - 1]
    if l:prev ==# '(' || l:prev ==# ','
      return " \<C-r>=jenking#MaybeOpenCall()\<CR>"
    endif
  endif
  return ' '
endfunction

" jenking#Find lists every symbol (top-level + receiver-scoped) whose name
" contains the given substring. Use it to confirm what got loaded when omni
" completion comes back empty.
function! jenking#Find(query) abort
  let l:hits = []
  let l:q = a:query
  for l:sym in s:symbols
    if l:q ==# '' || stridx(l:sym.word, l:q) >= 0
      call add(l:hits, printf('%-30s %s', l:sym.word, l:sym.menu))
    endif
  endfor
  for l:recv in s:receivers
    for l:m in s:members[l:recv]
      let l:qualified = l:recv . '.' . l:m.word
      if l:q ==# '' || stridx(l:qualified, l:q) >= 0
        call add(l:hits, printf('%-30s %s', l:qualified, l:m.menu))
      endif
    endfor
  endfor
  if empty(l:hits)
    echohl WarningMsg | echo 'jenking: no symbol matches ' . string(l:q) | echohl None
    return
  endif
  echo join(l:hits, "\n")
endfunction

" :JenkingStatus prints what's loaded — useful when omni completion comes up
" empty and you're not sure why.
command! JenkingStatus echo printf("steps=%d  globals=%d  receivers=%s", s:steps_count, s:globals_count, string(s:receivers))

" :JenkingFind <substring> lists matching symbols (top-level + receiver.member).
" Example: :JenkingFind archive  → see whether 'archive' is loaded.
command! -nargs=? JenkingFind call jenking#Find(<q-args>)
`)
	if rt != nil {
		b.WriteString(`
function! jenking#WriteBuffer() abort
  silent execute 'write! ' . fnameescape(g:jenking_buffer . '.tmp')
  call rename(g:jenking_buffer . '.tmp', g:jenking_buffer)
  echohl Comment | echom 'jenking: sent for validation…' | echohl None
endfunction

function! jenking#ReloadQF(timer) abort
  if !filereadable(g:jenking_errors) | return | endif
  let l:mtime = getftime(g:jenking_errors)
  if exists('s:qf_mtime') && s:qf_mtime ==# l:mtime | return | endif
  let s:qf_mtime = l:mtime
  execute 'cgetfile ' . fnameescape(g:jenking_errors)
  let l:n = len(getqflist())
  if l:n == 0
    echohl ModeMsg | echom 'jenking: validation OK (declarative checks only)' | echohl None
  else
    echohl WarningMsg | echom printf('jenking: %d validation issue(s) — :cnext to navigate', l:n) | echohl None
  endif
endfunction
`)
	}
	return b.String()
}

// renderPluginVim emits plugin/jenking.vim — wires globals + autocmds. Real
// behaviour lives under autoload/jenking.vim (referenced by name).
func renderPluginVim(rt *vimRuntime) string {
	var b strings.Builder
	b.WriteString(`" Generated by jenking — plugin/jenking.vim.
if exists('g:loaded_jenking') | finish | endif
let g:loaded_jenking = 1
`)
	if rt != nil {
		fmt.Fprintf(&b, "let g:jenking_runtime_dir = %s\n", vimStr(rt.dir))
		fmt.Fprintf(&b, "let g:jenking_buffer = %s\n", vimStr(rt.bufferTmp))
		fmt.Fprintf(&b, "let g:jenking_errors = %s\n", vimStr(rt.errorsQF))
	}
	b.WriteString(`
augroup JenkingSetup
  autocmd!
  autocmd BufRead,BufNewFile *.groovy,Jenkinsfile,*.jenkinsfile call jenking#Setup()
augroup END
`)
	if rt != nil {
		b.WriteString(`
augroup JenkingValidate
  autocmd!
  autocmd BufWritePost *.groovy call jenking#WriteBuffer()
augroup END

if has('timers')
  call timer_start(1500, function('jenking#ReloadQF'), {'repeat': -1})
endif
`)
	}
	return b.String()
}

// vimStr quotes s as a Vim double-quoted string literal. Double-quoted is
// used (not single-quoted) because user-GDSL doc strings routinely contain
// newlines, single quotes (apostrophes in Dutch / English prose), and code
// samples like 'demo.tar' — none of which Vim's single-quoted strings can
// represent. Vim's double-quoted escapes: \\ \" \n \t \r, plus we drop
// other ASCII control bytes to keep the generated file printable.
func vimStr(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 2)
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		default:
			if r < 0x20 {
				continue
			}
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// applyVimArgs returns a new *exec.Cmd that layers jenking's runtime on top
// of the user's vim/nvim. For non-vim editors (emacs, nano, vscode, …) the
// original cmd is returned unchanged.
//
// Strategy:
//   - --cmd 'set rtp^=…'        runs BEFORE the user's vimrc — adds our runtime
//     to the head of the runtimepath so after/syntax/groovy.vim gets sourced.
//   - -c 'runtime! plugin/jenking.vim'  runs AFTER user vimrc — ensures our
//     Setup() autocmd is wired even if the user's vimrc disabled plugin loading.
func applyVimArgs(cmd *exec.Cmd, rt *vimRuntime) *exec.Cmd {
	if cmd == nil || rt == nil {
		return cmd
	}
	bin := filepath.Base(cmd.Path)
	if !isVimBinary(bin) {
		return cmd
	}
	// Prepend our flags; keep the original positional args (file path last).
	extra := []string{
		"--cmd", "set rtp^=" + rt.dir,
		"-c", "runtime! plugin/jenking.vim",
	}
	newArgs := append([]string{cmd.Args[0]}, extra...)
	newArgs = append(newArgs, cmd.Args[1:]...)
	cmd.Args = newArgs
	return cmd
}

// isVimBinary reports whether the basename of an editor command is one of
// the vim-family editors we know how to inject into.
func isVimBinary(bin string) bool {
	switch strings.ToLower(strings.TrimSuffix(bin, ".exe")) {
	case "vim", "nvim", "gvim", "vi":
		return true
	}
	return false
}
